test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: GCS-local
  root: <%= Rails.root.join("storage") %>

production:
  service: GCS
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

google:
   service: GCS
   project: adhoc
#   credentials: <%= Rails.root.join("../keys/adhoc-gcs-key.json") %>
   bucket: adhoc_storage
   credentials: <%= Rails.root.join(json_key_io: StringIO.new(ENV['GOOGLE_CREDENTIALS'])) %>

google:
   service: GCS-local
   project: adhoc
   credentials: <%= Rails.root.join("../keys/adhoc-gcs-key.json") %>
   bucket: adhoc_storage
#   credentials: Google::Auth::ServiceAccountCredentials.make_creds(scope: 'https://www.googleapis.com/auth/drive', json_key_io: StringIO.new(ENV['GOOGLE_APPLICATION_CREDENTIALS']))
# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
